export const ROUTES = {
  ONBOARDING: '/onboarding',
  LOGIN: '/login',
  HOME: '/home',
  DISCOVER: '/discover',
  SEARCH: '/search',
  SEARCH_RESULTS: '/search/results',
  BOOKING_DETAIL: '/booking/detail',
  BOOKING_CHECKOUT: '/booking/checkout',
  TRIPS: '/trips',
  TRIP_DETAIL: (tripId: string) => `/trips/${tripId}`,
  DOCUMENTS: '/trips/documents',
  AIRPORT: '/airport',
  GATE: '/airport/gate',
  INFLIGHT: (flightId: string) => `/inflight/${flightId}`,
  IROPS: (flightId: string) => `/irops/${flightId}`,
  FAMILY: '/family',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  AI_COPILOT: '/ai/copilot',
  LOUNGE: '/lounge',
  TRIP_RECAP: '/trips/recap',
} as const;
