import { TripDocument } from '@/lib/types/document';
import { PersonaType } from '@/lib/types/user';

export const MOCK_TRIP_DOCUMENTS: TripDocument[] = [
  {
    id: 'doc-001',
    tripId: 'trip-001',
    type: 'passport',
    name: 'US Passport',
    holderName: 'Wei Chen',
    required: true,
    status: 'uploaded',
    expirationDate: '2030-08-15',
    uploadDate: '2026-03-20',
    fileSize: 250000,
    encrypted: true,
    metadata: { country: 'US', documentNumber: 'C12345678', issuedDate: '2020-08-15' },
  },
  {
    id: 'doc-002',
    tripId: 'trip-001',
    type: 'passport',
    name: 'US Passport',
    holderName: 'Lin Chen',
    required: true,
    status: 'uploaded',
    expirationDate: '2029-03-22',
    uploadDate: '2026-03-20',
    fileSize: 245000,
    encrypted: true,
    metadata: { country: 'US', documentNumber: 'C23456789', issuedDate: '2019-03-22' },
  },
  {
    id: 'doc-003',
    tripId: 'trip-001',
    type: 'passport',
    name: 'US Passport',
    holderName: 'Sophie Chen',
    required: true,
    status: 'uploaded',
    expirationDate: '2031-11-10',
    uploadDate: '2026-03-20',
    fileSize: 240000,
    encrypted: true,
    metadata: { country: 'US', documentNumber: 'C34567890', issuedDate: '2026-11-10' },
  },
  {
    id: 'doc-004',
    tripId: 'trip-001',
    type: 'passport',
    name: 'US Passport',
    holderName: 'Lucas Chen',
    required: true,
    status: 'uploaded',
    expirationDate: '2031-06-01',
    uploadDate: '2026-03-20',
    fileSize: 238000,
    encrypted: true,
    metadata: { country: 'US', documentNumber: 'C45678901', issuedDate: '2026-06-01' },
  },
  {
    id: 'doc-005',
    tripId: 'trip-001',
    type: 'insurance',
    name: 'Family Travel Insurance',
    holderName: 'Chen Family',
    required: true,
    status: 'uploaded',
    expirationDate: '2026-12-31',
    uploadDate: '2026-03-18',
    fileSize: 520000,
    encrypted: true,
    metadata: { documentNumber: 'TI-889234' },
  },
  {
    id: 'doc-006',
    tripId: 'trip-001',
    type: 'custom',
    name: 'Vaccination Records — Sophie',
    holderName: 'Sophie Chen',
    required: false,
    status: 'uploaded',
    expirationDate: undefined,
    uploadDate: '2026-03-15',
    fileSize: 180000,
    encrypted: true,
    metadata: {},
  },
  {
    id: 'doc-007',
    tripId: 'trip-001',
    type: 'custom',
    name: 'Vaccination Records — Lucas',
    holderName: 'Lucas Chen',
    required: false,
    status: 'uploaded',
    expirationDate: undefined,
    uploadDate: '2026-03-15',
    fileSize: 175000,
    encrypted: true,
    metadata: {},
  },
];

export const MOCK_GENERAL_DOCUMENTS: TripDocument[] = [
  {
    id: 'gen-001',
    type: 'insurance',
    name: 'Annual Health Insurance',
    holderName: 'Chen Family',
    required: false,
    status: 'uploaded',
    expirationDate: '2027-01-01',
    uploadDate: '2026-01-05',
    fileSize: 430000,
    encrypted: true,
    metadata: { documentNumber: 'BS-FAM-7712' },
  },
  {
    id: 'gen-002',
    type: 'custom',
    name: 'Frequent Flyer Card — HawaiianMiles',
    holderName: 'Wei Chen',
    required: false,
    status: 'uploaded',
    expirationDate: undefined,
    uploadDate: '2025-09-10',
    fileSize: 60000,
    encrypted: false,
    metadata: { documentNumber: 'HM-4412890' },
  },
];

export const MOCK_PREMIUM_DOCUMENTS: TripDocument[] = [
  {
    id: 'prem-001',
    tripId: 'trip-demo-002',
    type: 'passport',
    name: 'US Passport',
    holderName: 'Alexandra Whitmore',
    required: true,
    status: 'uploaded',
    expirationDate: '2033-02-18',
    uploadDate: '2026-02-01',
    fileSize: 260000,
    encrypted: true,
    metadata: { country: 'US', documentNumber: 'P98765432', issuedDate: '2023-02-18' },
  },
  {
    id: 'prem-002',
    tripId: 'trip-demo-002',
    type: 'insurance',
    name: 'Platinum Travel Protection',
    holderName: 'Alexandra Whitmore',
    required: true,
    status: 'uploaded',
    expirationDate: '2027-01-01',
    uploadDate: '2026-01-15',
    fileSize: 380000,
    encrypted: true,
    metadata: { documentNumber: 'PTP-ELITE-2241' },
  },
  {
    id: 'prem-003',
    tripId: 'trip-demo-002',
    type: 'visa',
    name: 'Japan eVisa',
    holderName: 'Alexandra Whitmore',
    required: true,
    status: 'uploaded',
    expirationDate: '2026-09-15',
    uploadDate: '2026-03-10',
    fileSize: 150000,
    encrypted: true,
    metadata: { country: 'JP', documentNumber: 'JP-EV-33891' },
  },
];

export const MOCK_BUSINESS_DOCUMENTS: TripDocument[] = [
  {
    id: 'biz-001',
    tripId: 'trip-biz-002',
    type: 'passport',
    name: 'US Passport',
    holderName: 'Marcus Webb',
    required: true,
    status: 'uploaded',
    expirationDate: '2029-07-22',
    uploadDate: '2026-01-20',
    fileSize: 255000,
    encrypted: true,
    metadata: { country: 'US', documentNumber: 'B55667788', issuedDate: '2019-07-22' },
  },
  {
    id: 'biz-002',
    tripId: 'trip-biz-002',
    type: 'custom',
    name: 'Global Entry Card',
    holderName: 'Marcus Webb',
    required: false,
    status: 'uploaded',
    expirationDate: '2028-03-10',
    uploadDate: '2026-01-20',
    fileSize: 120000,
    encrypted: true,
    metadata: { documentNumber: 'GE-90223145' },
  },
  {
    id: 'biz-003',
    tripId: 'trip-biz-002',
    type: 'custom',
    name: 'Corporate Travel Policy',
    holderName: 'Marcus Webb',
    required: false,
    status: 'uploaded',
    expirationDate: undefined,
    uploadDate: '2025-08-15',
    fileSize: 200000,
    encrypted: false,
    metadata: {},
  },
];

export function getDocumentsForPersona(persona: PersonaType): {
  tripDocuments: TripDocument[];
  generalDocuments: TripDocument[];
  tripLabel: string;
} {
  switch (persona) {
    case 'premium':
      return {
        tripDocuments: MOCK_PREMIUM_DOCUMENTS,
        generalDocuments: [MOCK_GENERAL_DOCUMENTS[2]],
        tripLabel: 'Tokyo Business Trip (SFO to NRT)',
      };
    case 'business':
      return {
        tripDocuments: MOCK_BUSINESS_DOCUMENTS,
        generalDocuments: MOCK_GENERAL_DOCUMENTS.slice(1),
        tripLabel: 'Chicago Quarterly Review (SFO to ORD)',
      };
    case 'family':
    default:
      return {
        tripDocuments: MOCK_TRIP_DOCUMENTS,
        generalDocuments: MOCK_GENERAL_DOCUMENTS,
        tripLabel: 'Hawaii Family Vacation (LAX to HNL)',
      };
  }
}
