import { TripDocument } from '@/lib/types/document';
import { PersonaType } from '@/lib/types/user';

export const MOCK_TRIP_DOCUMENTS: TripDocument[] = [
  {
    id: 'doc-001',
    tripId: 'trip-001',
    type: 'passport',
    name: 'US Passport',
    holderName: 'John Chen',
    required: true,
    status: 'uploaded',
    expirationDate: '2034-08-15',
    uploadDate: '2026-03-20',
    fileSize: 250000,
    encrypted: true,
    metadata: { country: 'US', documentNumber: 'C12345678', issuedDate: '2024-08-15' },
  },
  {
    id: 'doc-002',
    tripId: 'trip-001',
    type: 'passport',
    name: 'US Passport',
    holderName: 'Amy Chen',
    required: true,
    status: 'uploaded',
    expirationDate: '2032-03-22',
    uploadDate: '2026-03-20',
    fileSize: 245000,
    encrypted: true,
    metadata: { country: 'US', documentNumber: 'C23456789', issuedDate: '2022-03-22' },
  },
  {
    id: 'doc-003',
    tripId: 'trip-001',
    type: 'passport',
    name: 'US Passport',
    holderName: 'Zoe Chen',
    required: true,
    status: 'uploaded',
    expirationDate: '2029-11-10',
    uploadDate: '2026-03-20',
    fileSize: 240000,
    encrypted: true,
    metadata: { country: 'US', documentNumber: 'C34567890', issuedDate: '2024-11-10' },
  },
  {
    id: 'doc-004',
    tripId: 'trip-001',
    type: 'passport',
    name: 'US Passport',
    holderName: 'Max Chen',
    required: true,
    status: 'uploaded',
    expirationDate: '2030-06-01',
    uploadDate: '2026-03-20',
    fileSize: 238000,
    encrypted: true,
    metadata: { country: 'US', documentNumber: 'C45678901', issuedDate: '2025-06-01' },
  },
  {
    id: 'doc-005',
    tripId: 'trip-001',
    type: 'visa',
    name: 'UK Visitor Visa',
    holderName: undefined,
    required: true,
    status: 'required',
    expirationDate: undefined,
    uploadDate: undefined,
    fileSize: undefined,
    encrypted: false,
    metadata: { country: 'GB' },
  },
  {
    id: 'doc-006',
    tripId: 'trip-001',
    type: 'insurance',
    name: 'Family Travel Insurance',
    holderName: 'Chen Family',
    required: true,
    status: 'uploaded',
    expirationDate: '2026-04-30',
    uploadDate: '2026-03-18',
    fileSize: 520000,
    encrypted: true,
    metadata: { documentNumber: 'TI-2026-8834' },
  },
  {
    id: 'doc-007',
    tripId: 'trip-001',
    type: 'booking',
    name: 'Hotel Confirmation — The Savoy',
    holderName: 'John Chen',
    required: false,
    status: 'uploaded',
    expirationDate: undefined,
    uploadDate: '2026-03-15',
    fileSize: 180000,
    encrypted: false,
    metadata: { documentNumber: 'SAV-2026-4421' },
  },
  {
    id: 'doc-008',
    tripId: 'trip-001',
    type: 'booking',
    name: 'Tower of London Tickets',
    holderName: 'Chen Family',
    required: false,
    status: 'uploaded',
    expirationDate: undefined,
    uploadDate: '2026-03-22',
    fileSize: 95000,
    encrypted: false,
    metadata: { documentNumber: 'TOL-44829' },
  },
];

export const MOCK_GENERAL_DOCUMENTS: TripDocument[] = [
  {
    id: 'gen-001',
    type: 'insurance',
    name: 'Annual Health Insurance',
    holderName: 'Chen Family',
    required: false,
    status: 'uploaded',
    expirationDate: '2027-01-01',
    uploadDate: '2026-01-05',
    fileSize: 430000,
    encrypted: true,
    metadata: { documentNumber: 'BS-FAM-7712' },
  },
  {
    id: 'gen-002',
    type: 'custom',
    name: "Max's Asthma Action Plan",
    holderName: 'Max Chen',
    required: false,
    status: 'uploaded',
    expirationDate: '2027-03-15',
    uploadDate: '2026-03-15',
    fileSize: 120000,
    encrypted: true,
    metadata: {},
  },
  {
    id: 'gen-003',
    type: 'custom',
    name: 'Frequent Flyer Card — United MileagePlus',
    holderName: 'John Chen',
    required: false,
    status: 'uploaded',
    expirationDate: undefined,
    uploadDate: '2025-09-10',
    fileSize: 60000,
    encrypted: false,
    metadata: { documentNumber: 'MP-8823456' },
  },
];

export const MOCK_PREMIUM_DOCUMENTS: TripDocument[] = [
  {
    id: 'prem-001',
    tripId: 'trip-002',
    type: 'passport',
    name: 'US Passport',
    holderName: 'Alexandra Whitmore',
    required: true,
    status: 'uploaded',
    expirationDate: '2033-02-18',
    uploadDate: '2026-02-01',
    fileSize: 260000,
    encrypted: true,
    metadata: { country: 'US', documentNumber: 'P98765432', issuedDate: '2023-02-18' },
  },
  {
    id: 'prem-002',
    tripId: 'trip-002',
    type: 'insurance',
    name: 'Platinum Travel Protection',
    holderName: 'Alexandra Whitmore',
    required: true,
    status: 'uploaded',
    expirationDate: '2027-01-01',
    uploadDate: '2026-01-15',
    fileSize: 380000,
    encrypted: true,
    metadata: { documentNumber: 'PTP-ELITE-2241' },
  },
  {
    id: 'prem-003',
    tripId: 'trip-002',
    type: 'visa',
    name: 'Japan eVisa',
    holderName: 'Alexandra Whitmore',
    required: true,
    status: 'uploaded',
    expirationDate: '2026-09-15',
    uploadDate: '2026-03-10',
    fileSize: 150000,
    encrypted: true,
    metadata: { country: 'JP', documentNumber: 'JP-EV-33891' },
  },
];

export const MOCK_BUSINESS_DOCUMENTS: TripDocument[] = [
  {
    id: 'biz-001',
    tripId: 'trip-003',
    type: 'passport',
    name: 'US Passport',
    holderName: 'Marcus Rivera',
    required: true,
    status: 'uploaded',
    expirationDate: '2031-07-22',
    uploadDate: '2026-01-20',
    fileSize: 255000,
    encrypted: true,
    metadata: { country: 'US', documentNumber: 'B55667788', issuedDate: '2021-07-22' },
  },
  {
    id: 'biz-002',
    tripId: 'trip-003',
    type: 'insurance',
    name: 'Corporate Travel Insurance',
    holderName: 'Marcus Rivera',
    required: true,
    status: 'expiring-soon',
    expirationDate: '2026-04-15',
    uploadDate: '2025-10-01',
    fileSize: 310000,
    encrypted: true,
    metadata: { documentNumber: 'CTI-CORP-4456' },
  },
  {
    id: 'biz-003',
    tripId: 'trip-003',
    type: 'custom',
    name: 'Corporate Travel Policy',
    holderName: 'Marcus Rivera',
    required: false,
    status: 'uploaded',
    expirationDate: undefined,
    uploadDate: '2025-08-15',
    fileSize: 200000,
    encrypted: false,
    metadata: {},
  },
];

export function getDocumentsForPersona(persona: PersonaType): {
  tripDocuments: TripDocument[];
  generalDocuments: TripDocument[];
  tripLabel: string;
} {
  switch (persona) {
    case 'premium':
      return {
        tripDocuments: MOCK_PREMIUM_DOCUMENTS,
        generalDocuments: [MOCK_GENERAL_DOCUMENTS[2]],
        tripLabel: 'Tokyo Business Trip (SFO to NRT)',
      };
    case 'business':
      return {
        tripDocuments: MOCK_BUSINESS_DOCUMENTS,
        generalDocuments: MOCK_GENERAL_DOCUMENTS.slice(2),
        tripLabel: 'Chicago Quarterly Review (SFO to ORD)',
      };
    case 'family':
    default:
      return {
        tripDocuments: MOCK_TRIP_DOCUMENTS,
        generalDocuments: MOCK_GENERAL_DOCUMENTS,
        tripLabel: 'London Family Trip (SFO to LHR)',
      };
  }
}
