import { Trip } from '@/lib/types/trip';
import { AIRLINES } from '@/lib/constants/airlines';

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip-001',
    name: 'London Business Trip',
    status: 'upcoming',
    departure: { airport: 'SFO', city: 'San Francisco', date: '2026-04-15' },
    arrival: { airport: 'LHR', city: 'London', date: '2026-04-16' },
    flights: [
      {
        id: 'tf-001',
        flight: {
          id: 'FL-SFO-LHR-0',
          airline: AIRLINES.BA,
          flightNumber: 'BA0286',
          departure: { airport: 'SFO', city: 'San Francisco', time: '2026-04-15T17:20:00Z', terminal: 'I', gate: 'G96' },
          arrival: { airport: 'LHR', city: 'London', time: '2026-04-16T11:30:00Z', terminal: '5' },
          duration: 610,
          stops: 0,
          aircraft: 'Boeing 777-300ER',
          amenities: ['wifi', 'entertainment', 'meals', 'flatbed', 'lounge-access'],
          pricing: { economy: 892, premiumEconomy: 1428, business: 5240, first: 8920, currency: 'USD' },
          seatsAvailable: 8,
          operationalStatus: 'on-time',
        },
        status: 'on-time',
        seat: '14A',
        checkedIn: false,
      },
    ],
    passengers: [{ id: 'p1', name: 'Alexandra Sterling', type: 'adult', seat: '14A', meal: 'Vegetarian' }],
    hotel: { name: 'The Savoy', city: 'London', checkIn: '2026-04-16', checkOut: '2026-04-20', confirmationNumber: 'SAV-392847' },
    totalCost: 7640,
    currency: 'USD',
    confirmationNumber: 'AT-BA-7X3K9R',
    createdAt: '2026-03-20',
  },
  {
    id: 'trip-002',
    name: 'Tokyo Family Vacation',
    status: 'upcoming',
    departure: { airport: 'LAX', city: 'Los Angeles', date: '2026-05-20' },
    arrival: { airport: 'HND', city: 'Tokyo', date: '2026-05-21' },
    flights: [
      {
        id: 'tf-002',
        flight: {
          id: 'FL-LAX-HND-3',
          airline: AIRLINES.NH,
          flightNumber: 'NH0105',
          departure: { airport: 'LAX', city: 'Los Angeles', time: '2026-05-20T11:30:00Z', terminal: 'B', gate: 'B42' },
          arrival: { airport: 'HND', city: 'Tokyo', time: '2026-05-21T15:20:00Z', terminal: '3' },
          duration: 710,
          stops: 0,
          aircraft: 'Boeing 787-9',
          amenities: ['wifi', 'entertainment', 'meals', 'power'],
          pricing: { economy: 1240, premiumEconomy: 1984, business: 6120, first: 9800, currency: 'USD' },
          seatsAvailable: 22,
          operationalStatus: 'on-time',
        },
        status: 'on-time',
        checkedIn: false,
      },
    ],
    passengers: [
      { id: 'p2', name: 'Sarah Chen', type: 'adult' },
      { id: 'p3', name: 'David Chen', type: 'adult' },
      { id: 'p4', name: 'Emily Chen', type: 'child' },
      { id: 'p5', name: 'Lucas Chen', type: 'child' },
    ],
    totalCost: 5960,
    currency: 'USD',
    confirmationNumber: 'AT-NH-2M8F4P',
    createdAt: '2026-03-10',
  },
  {
    id: 'trip-003',
    name: 'New York Tech Summit',
    status: 'upcoming',
    departure: { airport: 'SFO', city: 'San Francisco', date: '2026-04-08' },
    arrival: { airport: 'JFK', city: 'New York', date: '2026-04-08' },
    flights: [
      {
        id: 'tf-003',
        flight: {
          id: 'FL-SFO-JFK-1',
          airline: AIRLINES.UA,
          flightNumber: 'UA0524',
          departure: { airport: 'SFO', city: 'San Francisco', time: '2026-04-08T07:00:00Z', terminal: '3', gate: 'F12' },
          arrival: { airport: 'JFK', city: 'New York', time: '2026-04-08T15:42:00Z', terminal: '7' },
          duration: 342,
          stops: 0,
          aircraft: 'Airbus A350-900',
          amenities: ['wifi', 'entertainment', 'meals', 'power'],
          pricing: { economy: 389, premiumEconomy: 622, business: 2180, first: 4200, currency: 'USD' },
          seatsAvailable: 34,
          operationalStatus: 'on-time',
        },
        status: 'on-time',
        seat: '3C',
        checkedIn: false,
      },
    ],
    passengers: [{ id: 'p6', name: 'Marcus Johnson', type: 'adult', seat: '3C', meal: 'Standard' }],
    totalCost: 2180,
    currency: 'USD',
    confirmationNumber: 'AT-UA-9K2D7L',
    createdAt: '2026-03-25',
  },
  // Completed trips for Trip Recap
  {
    id: 'trip-004',
    name: 'Singapore Grand Prix Weekend',
    status: 'completed',
    departure: { airport: 'SFO', city: 'San Francisco', date: '2026-03-10' },
    arrival: { airport: 'SIN', city: 'Singapore', date: '2026-03-11' },
    flights: [
      {
        id: 'tf-004',
        flight: {
          id: 'FL-SFO-SIN-0',
          airline: AIRLINES.SQ,
          flightNumber: 'SQ0001',
          departure: { airport: 'SFO', city: 'San Francisco', time: '2026-03-10T23:30:00Z', terminal: 'I', gate: 'G92' },
          arrival: { airport: 'SIN', city: 'Singapore', time: '2026-03-12T06:45:00Z', terminal: '3' },
          duration: 1035,
          stops: 0,
          aircraft: 'Airbus A350-900ULR',
          amenities: ['wifi', 'entertainment', 'meals', 'flatbed', 'lounge-access'],
          pricing: { economy: 1200, premiumEconomy: 2100, business: 6800, first: 12400, currency: 'USD' },
          seatsAvailable: 0,
          operationalStatus: 'arrived',
        },
        status: 'on-time',
        seat: '1A',
        checkedIn: true,
        boardingPass: 'BP-SQ001-1A',
      },
    ],
    passengers: [{ id: 'p7', name: 'Alexandra Sterling', type: 'adult', seat: '1A', meal: 'Chef\'s Tasting Menu' }],
    hotel: { name: 'Marina Bay Sands', city: 'Singapore', checkIn: '2026-03-12', checkOut: '2026-03-17', confirmationNumber: 'MBS-284716' },
    totalCost: 18200,
    currency: 'USD',
    confirmationNumber: 'AT-SQ-4R8N2K',
    createdAt: '2026-02-15',
  },
  {
    id: 'trip-005',
    name: 'Chicago Client Meeting',
    status: 'completed',
    departure: { airport: 'SFO', city: 'San Francisco', date: '2026-03-18' },
    arrival: { airport: 'ORD', city: 'Chicago', date: '2026-03-18' },
    flights: [
      {
        id: 'tf-005',
        flight: {
          id: 'FL-SFO-ORD-0',
          airline: AIRLINES.UA,
          flightNumber: 'UA0858',
          departure: { airport: 'SFO', city: 'San Francisco', time: '2026-03-18T06:15:00Z', terminal: '3', gate: 'E7' },
          arrival: { airport: 'ORD', city: 'Chicago', time: '2026-03-18T12:28:00Z', terminal: '1' },
          duration: 253,
          stops: 0,
          aircraft: 'Boeing 737 MAX 9',
          amenities: ['wifi', 'entertainment', 'power'],
          pricing: { economy: 320, premiumEconomy: 510, business: 1640, first: 3200, currency: 'USD' },
          seatsAvailable: 0,
          operationalStatus: 'arrived',
        },
        status: 'on-time',
        seat: '2A',
        checkedIn: true,
      },
    ],
    passengers: [{ id: 'p8', name: 'Marcus Johnson', type: 'adult', seat: '2A', meal: 'Standard' }],
    hotel: { name: 'The Peninsula Chicago', city: 'Chicago', checkIn: '2026-03-18', checkOut: '2026-03-20', confirmationNumber: 'PEN-583291' },
    totalCost: 2840,
    currency: 'USD',
    confirmationNumber: 'AT-UA-6H3M9P',
    createdAt: '2026-03-05',
  },
  {
    id: 'trip-006',
    name: 'Orlando Spring Break',
    status: 'completed',
    departure: { airport: 'LAX', city: 'Los Angeles', date: '2026-03-08' },
    arrival: { airport: 'MCO', city: 'Orlando', date: '2026-03-08' },
    flights: [
      {
        id: 'tf-006',
        flight: {
          id: 'FL-LAX-MCO-0',
          airline: AIRLINES.AA,
          flightNumber: 'AA2847',
          departure: { airport: 'LAX', city: 'Los Angeles', time: '2026-03-08T08:00:00Z', terminal: '4', gate: '47A' },
          arrival: { airport: 'MCO', city: 'Orlando', time: '2026-03-08T16:15:00Z', terminal: 'A' },
          duration: 315,
          stops: 0,
          aircraft: 'Airbus A321neo',
          amenities: ['wifi', 'entertainment', 'power'],
          pricing: { economy: 280, premiumEconomy: 450, business: 1200, first: 2400, currency: 'USD' },
          seatsAvailable: 0,
          operationalStatus: 'arrived',
        },
        status: 'on-time',
        checkedIn: true,
      },
    ],
    passengers: [
      { id: 'p9', name: 'Sarah Chen', type: 'adult' },
      { id: 'p10', name: 'David Chen', type: 'adult' },
      { id: 'p11', name: 'Emily Chen', type: 'child' },
      { id: 'p12', name: 'Lucas Chen', type: 'child' },
    ],
    totalCost: 4280,
    currency: 'USD',
    confirmationNumber: 'AT-AA-8K5R2N',
    createdAt: '2026-02-20',
  },
];

export function getTripsForPersona(persona: 'premium' | 'business' | 'family'): Trip[] {
  switch (persona) {
    case 'premium':
      return [MOCK_TRIPS[0], MOCK_TRIPS[3]]; // upcoming London + completed Singapore
    case 'business':
      return [MOCK_TRIPS[2], MOCK_TRIPS[4]]; // upcoming NY + completed Chicago
    case 'family':
      return [MOCK_TRIPS[1], MOCK_TRIPS[5]]; // upcoming Tokyo + completed Orlando
  }
}
