import { Trip } from '@/lib/types/trip';
import { AIRLINES } from '@/lib/constants/airlines';

export const MOCK_TRIPS: Trip[] = [
  // Demo Trip 1: JFK → SIN — DISRUPTED (departing in 3 days)
  {
    id: 'trip-demo-001',
    name: 'Singapore Business Trip',
    status: 'disrupted' as const,
    departure: { airport: 'JFK', city: 'New York', date: '2026-04-01' },
    arrival: { airport: 'SIN', city: 'Singapore', date: '2026-04-02' },
    flights: [
      {
        id: 'tf-demo-001',
        flight: {
          id: 'FL-JFK-SIN-DEMO',
          airline: AIRLINES.SQ,
          flightNumber: 'SQ25',
          departure: { airport: 'JFK', city: 'New York', time: '2026-04-01T22:25:00Z', terminal: '4', gate: 'B22' },
          arrival: { airport: 'SIN', city: 'Singapore', time: '2026-04-02T17:05:00Z', terminal: '3' },
          duration: 1120,
          stops: 0,
          aircraft: 'Airbus A350-900ULR',
          amenities: ['wifi', 'entertainment', 'meals', 'flatbed', 'lounge-access'] as const,
          pricing: { economy: 1400, premiumEconomy: 2450, business: 7200, first: 13500, currency: 'USD' },
          seatsAvailable: 12,
          operationalStatus: 'delayed' as const,
        },
        status: 'delayed' as const,
        seat: '14A',
        checkedIn: false,
      },
    ],
    passengers: [
      { id: 'p-demo-1', name: 'Alexandra Sterling', type: 'adult' as const, seat: '14A', meal: 'Vegetarian' },
      { id: 'p-demo-2', name: 'James Sterling', type: 'adult' as const, seat: '14C', meal: 'Standard' },
      { id: 'p-demo-3', name: 'Sophie Sterling', type: 'child' as const, seat: '14E' },
    ],
    hotel: { name: 'Marina Bay Sands', city: 'Singapore', checkIn: '2026-04-02', checkOut: '2026-04-07', confirmationNumber: 'MBS-847291' },
    totalCost: 24800,
    currency: 'USD',
    confirmationNumber: 'AT-SQ-3K7M9P',
    createdAt: '2026-03-15',
  },
  // Demo Trip 2: LAX → NRT — COMPLETED (2 weeks ago)
  {
    id: 'trip-demo-002',
    name: 'Tokyo Spring Getaway',
    status: 'completed' as const,
    departure: { airport: 'LAX', city: 'Los Angeles', date: '2026-03-15' },
    arrival: { airport: 'NRT', city: 'Tokyo', date: '2026-03-16' },
    flights: [
      {
        id: 'tf-demo-002',
        flight: {
          id: 'FL-LAX-NRT-DEMO',
          airline: AIRLINES.NH,
          flightNumber: 'NH0105',
          departure: { airport: 'LAX', city: 'Los Angeles', time: '2026-03-15T11:30:00Z', terminal: 'B', gate: 'B42' },
          arrival: { airport: 'NRT', city: 'Tokyo', time: '2026-03-16T15:50:00Z', terminal: '1' },
          duration: 700,
          stops: 0,
          aircraft: 'Boeing 787-9',
          amenities: ['wifi', 'entertainment', 'meals', 'flatbed', 'lounge-access'] as const,
          pricing: { economy: 1350, premiumEconomy: 2160, business: 6500, first: 11200, currency: 'USD' },
          seatsAvailable: 0,
          operationalStatus: 'arrived' as const,
        },
        status: 'on-time' as const,
        seat: '2K',
        checkedIn: true,
        boardingPass: 'BP-NH105-2K',
      },
    ],
    passengers: [{ id: 'p-demo-4', name: 'Alexandra Sterling', type: 'adult' as const, seat: '2K', meal: 'Japanese Set' }],
    hotel: { name: 'Aman Tokyo', city: 'Tokyo', checkIn: '2026-03-16', checkOut: '2026-03-22', confirmationNumber: 'AMN-529384' },
    totalCost: 15800,
    currency: 'USD',
    confirmationNumber: 'AT-NH-8R4K2M',
    createdAt: '2026-02-28',
  },
  // Demo Trip 3: SFO → LHR — UPCOMING (3 weeks out)
  {
    id: 'trip-demo-003',
    name: 'London Conference',
    status: 'upcoming' as const,
    departure: { airport: 'SFO', city: 'San Francisco', date: '2026-04-19' },
    arrival: { airport: 'LHR', city: 'London', date: '2026-04-20' },
    flights: [
      {
        id: 'tf-demo-003',
        flight: {
          id: 'FL-SFO-LHR-DEMO',
          airline: AIRLINES.BA,
          flightNumber: 'BA0286',
          departure: { airport: 'SFO', city: 'San Francisco', time: '2026-04-19T17:20:00Z', terminal: 'I', gate: 'G96' },
          arrival: { airport: 'LHR', city: 'London', time: '2026-04-20T11:30:00Z', terminal: '5' },
          duration: 610,
          stops: 0,
          aircraft: 'Boeing 777-300ER',
          amenities: ['wifi', 'entertainment', 'meals', 'flatbed', 'lounge-access'] as const,
          pricing: { economy: 892, premiumEconomy: 1428, business: 5240, first: 8920, currency: 'USD' },
          seatsAvailable: 14,
          operationalStatus: 'on-time' as const,
        },
        status: 'on-time' as const,
        seat: '7A',
        checkedIn: false,
      },
    ],
    passengers: [{ id: 'p-demo-5', name: 'Alexandra Sterling', type: 'adult' as const, seat: '7A', meal: 'Vegetarian' }],
    hotel: { name: 'The Savoy', city: 'London', checkIn: '2026-04-20', checkOut: '2026-04-24', confirmationNumber: 'SAV-681742' },
    totalCost: 8640,
    currency: 'USD',
    confirmationNumber: 'AT-BA-5N2H8K',
    createdAt: '2026-03-20',
  },
  // Demo Trip 4: JFK → CDG — UPCOMING (10 days out)
  {
    id: 'trip-demo-004',
    name: 'Paris Art & Design Week',
    status: 'upcoming' as const,
    departure: { airport: 'JFK', city: 'New York', date: '2026-04-08' },
    arrival: { airport: 'CDG', city: 'Paris', date: '2026-04-09' },
    flights: [
      {
        id: 'tf-demo-004',
        flight: {
          id: 'FL-JFK-CDG-DEMO',
          airline: AIRLINES.AF,
          flightNumber: 'AF0007',
          departure: { airport: 'JFK', city: 'New York', time: '2026-04-08T19:00:00Z', terminal: '1', gate: 'A14' },
          arrival: { airport: 'CDG', city: 'Paris', time: '2026-04-09T08:30:00Z', terminal: '2E' },
          duration: 450,
          stops: 0,
          aircraft: 'Airbus A350-900',
          amenities: ['wifi', 'entertainment', 'meals', 'flatbed', 'lounge-access'] as const,
          pricing: { economy: 980, premiumEconomy: 1680, business: 5800, first: 9400, currency: 'USD' },
          seatsAvailable: 18,
          operationalStatus: 'on-time' as const,
        },
        status: 'on-time' as const,
        seat: '3A',
        checkedIn: false,
      },
    ],
    passengers: [{ id: 'p-demo-6', name: 'Alexandra Sterling', type: 'adult' as const, seat: '3A', meal: 'French Tasting' }],
    hotel: { name: 'Le Bristol Paris', city: 'Paris', checkIn: '2026-04-09', checkOut: '2026-04-13', confirmationNumber: 'BRS-492183' },
    totalCost: 12400,
    currency: 'USD',
    confirmationNumber: 'AT-AF-7K3M9R',
    createdAt: '2026-03-22',
  },
  // Original trip-001 (kept for reference)
  {
    id: 'trip-001',
    name: 'London Business Trip',
    status: 'upcoming',
    departure: { airport: 'SFO', city: 'San Francisco', date: '2026-04-15' },
    arrival: { airport: 'LHR', city: 'London', date: '2026-04-16' },
    flights: [
      {
        id: 'tf-001',
        flight: {
          id: 'FL-SFO-LHR-0',
          airline: AIRLINES.BA,
          flightNumber: 'BA0286',
          departure: { airport: 'SFO', city: 'San Francisco', time: '2026-04-15T17:20:00Z', terminal: 'I', gate: 'G96' },
          arrival: { airport: 'LHR', city: 'London', time: '2026-04-16T11:30:00Z', terminal: '5' },
          duration: 610,
          stops: 0,
          aircraft: 'Boeing 777-300ER',
          amenities: ['wifi', 'entertainment', 'meals', 'flatbed', 'lounge-access'],
          pricing: { economy: 892, premiumEconomy: 1428, business: 5240, first: 8920, currency: 'USD' },
          seatsAvailable: 8,
          operationalStatus: 'on-time',
        },
        status: 'on-time',
        seat: '14A',
        checkedIn: false,
      },
    ],
    passengers: [{ id: 'p1', name: 'Alexandra Sterling', type: 'adult', seat: '14A', meal: 'Vegetarian' }],
    hotel: { name: 'The Savoy', city: 'London', checkIn: '2026-04-16', checkOut: '2026-04-20', confirmationNumber: 'SAV-392847' },
    totalCost: 7640,
    currency: 'USD',
    confirmationNumber: 'AT-BA-7X3K9R',
    createdAt: '2026-03-20',
  },
  // Business persona trips
  {
    id: 'trip-biz-001',
    name: 'Chicago Strategy Offsite',
    status: 'upcoming' as const,
    departure: { airport: 'SFO', city: 'San Francisco', date: '2026-03-30' },
    arrival: { airport: 'ORD', city: 'Chicago', date: '2026-03-30' },
    flights: [
      {
        id: 'tf-biz-001',
        flight: {
          id: 'FL-SFO-ORD-BIZ',
          airline: AIRLINES.UA,
          flightNumber: 'UA0456',
          departure: { airport: 'SFO', city: 'San Francisco', time: '2026-03-30T07:15:00Z', terminal: '3', gate: 'F14' },
          arrival: { airport: 'ORD', city: 'Chicago', time: '2026-03-30T13:22:00Z', terminal: '1' },
          duration: 247,
          stops: 0,
          aircraft: 'Boeing 737 MAX 9',
          amenities: ['wifi', 'power', 'entertainment'] as const,
          pricing: { economy: 342, premiumEconomy: 548, business: 1860, first: 3400, currency: 'USD' },
          seatsAvailable: 28,
          operationalStatus: 'delayed' as const,
        },
        status: 'delayed' as const,
        seat: '8C',
        checkedIn: false,
      },
    ],
    passengers: [{ id: 'p-biz-1', name: 'Marcus Webb', type: 'adult' as const, seat: '8C', meal: 'Standard' }],
    hotel: { name: 'The Langham Chicago', city: 'Chicago', checkIn: '2026-03-30', checkOut: '2026-04-02', confirmationNumber: 'LNG-482916' },
    totalCost: 3240,
    currency: 'USD',
    confirmationNumber: 'AT-UA-8K2M5P',
    createdAt: '2026-03-20',
  },
  {
    id: 'trip-biz-002',
    name: 'London Fintech Summit',
    status: 'upcoming' as const,
    departure: { airport: 'BOS', city: 'Boston', date: '2026-04-12' },
    arrival: { airport: 'LHR', city: 'London', date: '2026-04-13' },
    flights: [
      {
        id: 'tf-biz-002',
        flight: {
          id: 'FL-BOS-LHR-BIZ',
          airline: AIRLINES.BA,
          flightNumber: 'BA0212',
          departure: { airport: 'BOS', city: 'Boston', time: '2026-04-12T19:45:00Z', terminal: 'E', gate: 'C24' },
          arrival: { airport: 'LHR', city: 'London', time: '2026-04-13T07:20:00Z', terminal: '5' },
          duration: 395,
          stops: 0,
          aircraft: 'Airbus A350-1000',
          amenities: ['wifi', 'entertainment', 'meals', 'flatbed', 'lounge-access'] as const,
          pricing: { economy: 680, premiumEconomy: 1250, business: 4800, first: 8200, currency: 'USD' },
          seatsAvailable: 16,
          operationalStatus: 'on-time' as const,
        },
        status: 'on-time' as const,
        seat: '5A',
        checkedIn: false,
      },
    ],
    passengers: [{ id: 'p-biz-2', name: 'Marcus Webb', type: 'adult' as const, seat: '5A', meal: 'Standard' }],
    hotel: { name: 'The Ned London', city: 'London', checkIn: '2026-04-13', checkOut: '2026-04-16', confirmationNumber: 'NED-739281' },
    totalCost: 6800,
    currency: 'USD',
    confirmationNumber: 'AT-BA-3N7K9R',
    createdAt: '2026-03-22',
  },
  {
    id: 'trip-biz-003',
    name: 'Seattle Client Pitch',
    status: 'completed' as const,
    departure: { airport: 'DEN', city: 'Denver', date: '2026-03-22' },
    arrival: { airport: 'SEA', city: 'Seattle', date: '2026-03-22' },
    flights: [
      {
        id: 'tf-biz-003',
        flight: {
          id: 'FL-DEN-SEA-BIZ',
          airline: AIRLINES.AS,
          flightNumber: 'AS0431',
          departure: { airport: 'DEN', city: 'Denver', time: '2026-03-22T06:30:00Z', terminal: 'B', gate: 'B36' },
          arrival: { airport: 'SEA', city: 'Seattle', time: '2026-03-22T08:45:00Z', terminal: 'N' },
          duration: 195,
          stops: 0,
          aircraft: 'Boeing 737-900ER',
          amenities: ['wifi', 'power', 'entertainment'] as const,
          pricing: { economy: 289, premiumEconomy: 462, business: 1420, first: 2800, currency: 'USD' },
          seatsAvailable: 0,
          operationalStatus: 'arrived' as const,
        },
        status: 'on-time' as const,
        seat: '4D',
        checkedIn: true,
        boardingPass: 'BP-AS431-4D',
      },
    ],
    passengers: [{ id: 'p-biz-3', name: 'Marcus Webb', type: 'adult' as const, seat: '4D', meal: 'Standard' }],
    hotel: { name: 'Four Seasons Seattle', city: 'Seattle', checkIn: '2026-03-22', checkOut: '2026-03-24', confirmationNumber: 'FSS-281947' },
    totalCost: 2860,
    currency: 'USD',
    confirmationNumber: 'AT-AS-5M2H8K',
    createdAt: '2026-03-10',
  },
  // Completed trips for Trip Recap
  {
    id: 'trip-004',
    name: 'Singapore Grand Prix Weekend',
    status: 'completed',
    departure: { airport: 'SFO', city: 'San Francisco', date: '2026-03-10' },
    arrival: { airport: 'SIN', city: 'Singapore', date: '2026-03-11' },
    flights: [
      {
        id: 'tf-004',
        flight: {
          id: 'FL-SFO-SIN-0',
          airline: AIRLINES.SQ,
          flightNumber: 'SQ0001',
          departure: { airport: 'SFO', city: 'San Francisco', time: '2026-03-10T23:30:00Z', terminal: 'I', gate: 'G92' },
          arrival: { airport: 'SIN', city: 'Singapore', time: '2026-03-12T06:45:00Z', terminal: '3' },
          duration: 1035,
          stops: 0,
          aircraft: 'Airbus A350-900ULR',
          amenities: ['wifi', 'entertainment', 'meals', 'flatbed', 'lounge-access'],
          pricing: { economy: 1200, premiumEconomy: 2100, business: 6800, first: 12400, currency: 'USD' },
          seatsAvailable: 0,
          operationalStatus: 'arrived',
        },
        status: 'on-time',
        seat: '1A',
        checkedIn: true,
        boardingPass: 'BP-SQ001-1A',
      },
    ],
    passengers: [{ id: 'p7', name: 'Alexandra Sterling', type: 'adult', seat: '1A', meal: 'Chef\'s Tasting Menu' }],
    hotel: { name: 'Marina Bay Sands', city: 'Singapore', checkIn: '2026-03-12', checkOut: '2026-03-17', confirmationNumber: 'MBS-284716' },
    totalCost: 18200,
    currency: 'USD',
    confirmationNumber: 'AT-SQ-4R8N2K',
    createdAt: '2026-02-15',
  },
  // Family persona trips
  {
    id: 'trip-fam-001',
    name: 'Hawaii Family Vacation',
    status: 'upcoming' as const,
    departure: { airport: 'LAX', city: 'Los Angeles', date: '2026-04-03' },
    arrival: { airport: 'HNL', city: 'Honolulu', date: '2026-04-03' },
    flights: [
      {
        id: 'tf-fam-001',
        flight: {
          id: 'FL-LAX-HNL-FAM',
          airline: AIRLINES.HA,
          flightNumber: 'HA0011',
          departure: { airport: 'LAX', city: 'Los Angeles', time: '2026-04-03T08:30:00Z', terminal: '5', gate: '51A' },
          arrival: { airport: 'HNL', city: 'Honolulu', time: '2026-04-03T11:45:00Z', terminal: '1' },
          duration: 345,
          stops: 0,
          aircraft: 'Airbus A321neo',
          amenities: ['wifi', 'entertainment', 'power'] as const,
          pricing: { economy: 380, premiumEconomy: 620, business: 1800, first: 3200, currency: 'USD' },
          seatsAvailable: 42,
          operationalStatus: 'on-time' as const,
        },
        status: 'on-time' as const,
        checkedIn: false,
      },
    ],
    passengers: [
      { id: 'p-fam-1', name: 'Wei Chen', type: 'adult' as const, seat: '24A', meal: 'Standard' },
      { id: 'p-fam-2', name: 'Lin Chen', type: 'adult' as const, seat: '24B', meal: 'Vegetarian' },
      { id: 'p-fam-3', name: 'Sophie Chen', type: 'child' as const, seat: '24C', meal: 'Kids Chicken Nuggets' },
      { id: 'p-fam-4', name: 'Lucas Chen', type: 'child' as const, seat: '24D', meal: 'Kids Mac & Cheese' },
    ],
    hotel: { name: 'Hilton Hawaiian Village', city: 'Honolulu', checkIn: '2026-04-03', checkOut: '2026-04-10', confirmationNumber: 'HHV-594817' },
    totalCost: 6840,
    currency: 'USD',
    confirmationNumber: 'AT-HA-2K8M4P',
    createdAt: '2026-03-15',
  },
  {
    id: 'trip-fam-002',
    name: 'Cancun Spring Break',
    status: 'completed' as const,
    departure: { airport: 'PHX', city: 'Phoenix', date: '2025-12-28' },
    arrival: { airport: 'CUN', city: 'Cancun', date: '2025-12-28' },
    flights: [
      {
        id: 'tf-fam-002',
        flight: {
          id: 'FL-PHX-CUN-FAM',
          airline: AIRLINES.WN,
          flightNumber: 'WN1847',
          departure: { airport: 'PHX', city: 'Phoenix', time: '2025-12-28T10:15:00Z', terminal: '4', gate: 'D8' },
          arrival: { airport: 'CUN', city: 'Cancun', time: '2025-12-28T16:30:00Z', terminal: '3' },
          duration: 255,
          stops: 0,
          aircraft: 'Boeing 737 MAX 8',
          amenities: ['wifi', 'entertainment'] as const,
          pricing: { economy: 245, premiumEconomy: 0, business: 0, first: 0, currency: 'USD' },
          seatsAvailable: 0,
          operationalStatus: 'arrived' as const,
        },
        status: 'on-time' as const,
        checkedIn: true,
      },
    ],
    passengers: [
      { id: 'p-fam-5', name: 'Wei Chen', type: 'adult' as const },
      { id: 'p-fam-6', name: 'Lin Chen', type: 'adult' as const },
      { id: 'p-fam-7', name: 'Sophie Chen', type: 'child' as const },
      { id: 'p-fam-8', name: 'Lucas Chen', type: 'child' as const },
    ],
    totalCost: 3920,
    currency: 'USD',
    confirmationNumber: 'AT-WN-7N4K2R',
    createdAt: '2025-11-15',
  },
];

export function getTripsForPersona(persona: 'premium' | 'business' | 'family'): Trip[] {
  switch (persona) {
    case 'premium':
      return MOCK_TRIPS.filter(t => ['trip-demo-001', 'trip-demo-002', 'trip-demo-003', 'trip-demo-004'].includes(t.id));
    case 'business':
      return MOCK_TRIPS.filter(t => ['trip-biz-001', 'trip-biz-002', 'trip-biz-003'].includes(t.id));
    case 'family':
      return MOCK_TRIPS.filter(t => ['trip-fam-001', 'trip-fam-002'].includes(t.id));
  }
}
